### PR TITLE
Add support for 'resource' parameter in Microsoft Online

### PR DESCRIPTION
**Pull request by realflash**
Mike,

My working code for Azure AD suddenly stopped working last week. It seems MS made a previously optional parameter ('resource') mandatory. These commits require the user to specify this parameter. It's a good thing because it probably makes this module compatible with a bunch of MS endpoints that it wouldn't have otherwise been. Sample code and docs also updated.

I added a test unit for this module, and was able to run it and the Spotify test successfully using the updated code. However, there is some outage at the Google Developer site that means I couldn't register an app for testing purposes, so there's still no Google Drive test unit. Perhaps you can test it if you still have an active app for this purpose.

### CODE REVIEW

**Comment by realflash** [comment]
Added another commit which stores the new refresh token that comes back when an access token is refreshed. This extends the time for which library can operate without re-authorising from 14 to 90 days.

**Comment by mschilli** [comment]
Hi Ian, thanks for this, sorry about the delay, I finally got around looking at the changes. I've tried obtaining an access token via the provided eg/microsoft-online-token-init script but got a "bad request" error message from the Microsoft Online site ... is it working on your end?

**Comment by realflash** [comment]
I'll try it again - been a few months.

## Regards,

Ian Gibbs
E: ian@flash.org.uk
M: 07815 142001

**Comment by realflash** [comment]
Will re-open this pull request with a new solution re-based on more current master

**Pull request closed without merging**
